#!/usr/bin/env python
"""Generate the report's LaTeX tables directly from the score tables.

WHY THIS IS A TOOL AND NOT TYPING
---------------------------------
`Guideline_for__Thesis__Writing.pdf` requires standard deviations with every
measurement. That is a constraint on the ANALYSIS, not the prose: a mean typed
into a .tex file by hand has no dispersion attached and no way to acquire one,
and it silently goes stale the moment a run is rescored. Every number the report
quotes is therefore emitted from the parquet that produced it, with its sd, and
regenerated by rerunning this script.

It also enforces the guideline's table rules, which are easy to breach by hand:
`booktabs` rules only, no vertical lines, every abbreviation expanded in the
caption, and a label so the text can reference the table (the guideline requires
that every table IS referenced).

Usage:
  python tools/make_report_tables.py --scores $WORK/prl26/results/scores \\
      --out report/tables
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]

# The paper's Table 1, for the comparison column. Quoted, not recomputed.
PAPER = {"infu": {"id": 0.209, "clip": 0.318, "pick": 0.221},
         "pulid": {"id": 0.225, "clip": 0.286, "pick": 0.212}}


def ms(series, fmt="%.4f"):
    """mean +/- sd, or a dash when undefined. The guideline requires the sd."""
    v = pd.to_numeric(series, errors="coerce").dropna()
    if len(v) == 0:
        return "--"
    if len(v) == 1:
        return fmt % v.iloc[0]
    return f"${fmt % v.mean()} \\pm {fmt % v.std(ddof=1)}$"


def tex_table(caption_short, caption_long, label, header, rows, align=None):
    """A booktabs table: horizontal rules only, never a vertical line."""
    ncol = len(header)
    align = align or ("l" + "r" * (ncol - 1))
    out = ["\\begin{table}[t]", "  \\centering",
           f"  \\caption[{caption_short}]{{{caption_long}}}",
           f"  \\label{{{label}}}",
           f"  \\begin{{tabular}}{{{align}}}", "    \\toprule",
           "    " + " & ".join(header) + " \\\\", "    \\midrule"]
    for r in rows:
        if r is None:
            out.append("    \\midrule")
            continue
        out.append("    " + " & ".join(str(c) for c in r) + " \\\\")
    out += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    return "\n".join(out)


def t_part1_headline(S):
    a = pd.read_parquet(S / "infu_aes2_manifest_repro.parquet")
    b = pd.read_parquet(S / "pulid_manifest_repro.parquet")
    rows = []
    for name, key, col in [("ID Loss (antelopev2)", "id", "id_loss_antelope"),
                           ("ID Loss (buffalo\\_l)", None, "id_loss_buffalo"),
                           ("CLIPScore (ViT-B/32)", "clip", "clipscore_b32"),
                           ("CLIPScore (ViT-L/14)", None, "clipscore_l14"),
                           ("PickScore ($/100$)", "pick", "pickscore_paper")]:
        rows.append([name, ms(a[col]), ms(b[col]),
                     f"{PAPER['infu'][key]:.3f}" if key else "--",
                     f"{PAPER['pulid'][key]:.3f}" if key else "--"])
    rows.append(None)
    # A detection rate is a proportion, not a sample of a continuous quantity.
    # Quoting the standard deviation of the 0/1 indicator would satisfy the
    # guideline's letter and mislead: it is a deterministic function of the rate
    # and carries no information the rate does not. Report the count instead.
    def rate(d):
        k = int(d["face_detected"].astype(bool).sum())
        return f"{k / len(d):.3f} ({k}/{len(d)})"
    rows.append(["Face detection rate", rate(a), rate(b), "--", "--"])
    return tex_table(
        "Part 1 reproduction",
        "Part 1, $n=1500$ cells per method, mean $\\pm$ standard deviation. "
        "Paper columns are the values reported by Jiang et al. and are not "
        "recomputed. ID Loss is $1-\\cos$ similarity of ArcFace embeddings "
        "(lower is better); it is undefined where no face is detected, so its "
        "$n$ is the detection count rather than 1500. Face detection rate is "
        "reported as a metric in its own right because it determines which "
        "cells ID Loss can use. InfU denotes InfiniteYou (aes\\_stage2).",
        "tab:part1", ["Metric", "InfU", "PuLID", "InfU (paper)", "PuLID (paper)"],
        rows, align="lccrr")


def t_part1_strata(S):
    """Both methods, because the composition argument needs both.

    Showing only InfU leaves open that the stratum pattern is a property of InfU
    rather than of the benchmark. If both methods degrade on the same axis, the
    axis is doing the work.
    """
    a = pd.read_parquet(S / "infu_aes2_manifest_repro.parquet")
    b = pd.read_parquet(S / "pulid_manifest_repro.parquet")
    rows = []
    for stratum in ["closeup", "waist", "full"]:
        da, db = a[a["face_size"] == stratum], b[b["face_size"] == stratum]
        rows.append([stratum, len(da),
                     ms(da["face_detected"].astype(float), "%.3f"),
                     ms(da["id_loss_antelope"]),
                     ms(db["face_detected"].astype(float), "%.3f"),
                     ms(db["id_loss_antelope"])])
    return tex_table(
        "Part 1 by face size",
        "Both methods stratified by the face-size axis of the benchmark, mean "
        "$\pm$ standard deviation. Detection and identity loss degrade together "
        "along the same axis for both methods, which identifies the axis rather "
        "than either implementation as the source. The full-body stratum is "
        "34\% of the benchmark by design; the original work varies face size "
        "but does not publish its marginals, so a differently weighted benchmark "
        "reports a different absolute ID Loss for an identical model. Note that "
        "the close-up stratum alone remains well above the published overall "
        "mean, so composition accounts for part of the gap and not all of it.",
        "tab:strata",
        ["Face size", "$n$", "Det.\ InfU", "ID Loss InfU",
         "Det.\ PuLID", "ID Loss PuLID"],
        rows)


def t_controls(S):
    """The two late controls: authors' identities, and the text-only ceiling.

    Returns None when neither has been scored yet, so the table simply does not
    appear rather than the build failing.
    """
    pid_f = S / "paperid_infu_manifest_paperid.parquet"
    ceil_f = S / "ceiling_prompts.parquet"
    if not pid_f.exists() and not ceil_f.exists():
        return None

    bench = pd.read_parquet(S / "infu_aes2_manifest_repro.parquet")
    rows = []

    if pid_f.exists():
        pid = pd.read_parquet(pid_f)
        rows.append(["InfU, this benchmark's identities (FRLL)", len(bench),
                     ms(bench["face_detected"].astype(float), "%.3f"),
                     ms(bench["id_loss_antelope"]), "--"])
        rows.append(["InfU, the authors' own example portraits", len(pid),
                     ms(pid["face_detected"].astype(float), "%.3f"),
                     ms(pid["id_loss_antelope"]), "--"])
        rows.append(None)

    if ceil_f.exists():
        ceil = pd.read_parquet(ceil_f)
        infu_c = ms(bench["clipscore_b32"])
        try:
            pul = pd.read_parquet(S / "pulid_manifest_repro.parquet")
            pul_c = ms(pul["clipscore_b32"])
        except Exception:                      # noqa: BLE001
            pul_c = "--"
        rows.append(["FLUX.1-dev, text only (ceiling)", len(ceil), "--", "--",
                     ms(ceil["clipscore_b32"])])
        rows.append(["InfU", len(bench), "--", "--", infu_c])
        rows.append(["PuLID", "--", "--", "--", pul_c])

    return tex_table(
        "Late controls",
        "Two controls added after the main runs. The upper block isolates the "
        "identity set: the authors' own example portraits are the only "
        "identities whose provenance is certain, and every other factor is held "
        "fixed. The lower block gives the text-only CLIPScore ceiling on this "
        "benchmark, which is the quantity the original work's text-alignment "
        "claim is stated against; it reports closing 66.7\% of the gap between "
        "the baseline and that ceiling.",
        "tab:controls",
        ["Condition", "$n$", "Detection", "ID Loss", "CLIPScore"],
        rows)


def t_bounds(S):
    j = json.loads((S / "part1_headline.json").read_text())
    rows = []
    for metric, label in [("id_loss_antelope", "ID Loss (antelopev2)"),
                          ("id_loss_buffalo", "ID Loss (buffalo\\_l)")]:
        b = j.get("bounds", {}).get(metric)
        if not b:
            continue
        rows.append([label,
                     f"{b['complete_a']:.4f}", f"{b['complete_b']:.4f}",
                     f"{b['diff_complete']:+.4f}",
                     f"{b['imputed_a']:.4f}", f"{b['imputed_b']:.4f}",
                     f"{b['diff_imputed']:+.4f}",
                     "yes" if b["sign_stable"] else "no"])
    return tex_table(
        "Detection-bounded comparison",
        "The InfU--PuLID comparison bounded against differential face "
        "detection. Complete case uses only cells where both methods produced "
        "a detectable face; the worst case charges every undetected cell the "
        "largest loss observed anywhere. Complete-case analysis rewards a "
        "method for failing on the cells it finds hardest, because failure "
        "removes the evidence, so the truth lies between the two columns. "
        "A negative difference favours PuLID.",
        "tab:bounds",
        ["Metric", "InfU", "PuLID", "$\\Delta$",
         "InfU", "PuLID", "$\\Delta$", "Stable"],
        rows, align="lrrrrrrc")


def t_floor(S):
    f = pd.read_parquet(S / "id_floor.parquet")
    rows = []
    for (lvl, name), g in f.groupby(["level", "filter"], sort=True):
        rows.append([name.replace("_", "\\_"), len(g),
                     ms(g["id_loss_antelope"]), ms(g["id_loss_buffalo"])])
    return tex_table(
        "ArcFace domain-shift floor",
        "Identity loss caused by non-photographic rendering alone, with "
        "geometry held fixed. Each reference photograph is filtered and scored "
        "against itself, so the person and the landmark geometry are identical "
        "by construction and the filters are verified sub-pixel against "
        "fiducial marks. Values are mean $\\pm$ standard deviation over eight "
        "identities. The painterly band (stylize\\_25 to stylize\\_60) is "
        "comparable in magnitude to the entire ID Loss of the generated "
        "images, which bounds what ID Loss can establish under stylisation. "
        "These filters preserve the photograph's shading and structure whereas "
        "a diffusion model reinterprets them, so this is a lower bound.",
        "tab:floor",
        ["Filter", "$n$", "ID Loss (antelopev2)", "ID Loss (buffalo\\_l)"], rows)


def t_part2(S):
    rows = []
    for method in ["infu", "pulid"]:
        j = json.loads((S / f"part2_{method}.json").read_text())
        name = "InfU" if method == "infu" else "PuLID"
        for metric, label in [("id_loss_antelope", "ID Loss"),
                              ("style_score", "Style adoption"),
                              ("fmi_photo", "FMI (photo form)")]:
            for r in j["metrics"].get(metric, []):
                star = "$^{*}$" if r.get("significant") else ""
                rows.append([name, label, r["style"].replace("_", "\\_"),
                             r["n"], f"{r['median']:+.4f}{star}",
                             f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}]"])
        rows.append(None)
    if rows and rows[-1] is None:
        rows.pop()
    return tex_table(
        "Part 2 paired style deltas",
        "Part 2, styled minus photoreal control, matched within cell so that "
        "both share an identity, a base prompt and a latent. Values are "
        "medians with bootstrap 95\\% confidence intervals; the test is the "
        "Wilcoxon signed-rank test and $^{*}$ marks significance after Holm "
        "correction across the three styles. FMI denotes the Face Masking "
        "Index, for which a positive value indicates the face resisted "
        "stylisation more than the background did. Style adoption is CLIP "
        "similarity to the condition's own style phrase. The ID Loss and "
        "style-adoption rows must be read together: a method that does not "
        "adopt a style preserves identity trivially.",
        "tab:part2",
        ["Method", "Metric", "Style", "$n$", "Median $\\Delta$", "95\\% CI"],
        rows, align="llrrrr")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scores", required=True)
    ap.add_argument("--out", default="report/tables")
    a = ap.parse_args()

    S = Path(a.scores)
    out = ROOT / a.out if not Path(a.out).is_absolute() else Path(a.out)
    out.mkdir(parents=True, exist_ok=True)

    builders = [("part1", t_part1_headline), ("strata", t_part1_strata),
                ("bounds", t_bounds), ("floor", t_floor), ("part2", t_part2),
                ("controls", t_controls)]
    made = []
    for name, fn in builders:
        try:
            tex = fn(S)
        except FileNotFoundError as e:
            print(f"  skip {name}: missing {Path(str(e).split()[-1]).name}")
            continue
        if tex is None:
            print(f"  skip {name}: inputs not scored yet")
            continue
        (out / f"{name}.tex").write_text(tex, encoding="ascii")
        made.append(name)
        print(f"  wrote {out / (name + '.tex')}")

    print(f"\n{len(made)} tables: {', '.join(made)}")
    print("Each uses booktabs rules only and carries a label, so the text can")
    print("reference it -- the guideline requires every table to be referenced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
